### ISSUE TITLE
ERROR: java.lang.UnsatisfiedLinkError: dlopen failed: library "libsong-actions.so" not found

### ISSUE THREAD

**Issue by donenoyes** [Lk91111/AVA_Music#1]
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsong-actions.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.lk.ava.activities.MainActivity.onCreate(MainActivity.kt:80)
```

Line: 80 of MainActivity.kt:

`System.loadLibrary("song-actions")`

How to resolve this? The error occurs when trying to open the App after installing.

**Comment by Lk91111** [comment]
In which device you got this error, I mean that type of error doesn't show on any android device.
